services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    restart: always
  backend:
    build: backend
    depends_on:
      database:
        condition: service_healthy
    environment:
      - JWT_SECRET=byt_en_stark_hemlighet_h√§r
      - JWT_EXPIRY=7d
      - PGURI=postgres://postgres:secret@database:5432/smultronstallen
    ports:
      - "3000:3000"
  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=smultronstallen
      - POSTGRES_USER=postgres
    healthcheck:
      test: "pg_isready --username=postgres"
      interval: 5s
      retries: 5
    volumes:
      - ./data:/var/lib/postgresql
    ports:
      - "5433:5432"
